# Logistic_Regression

Based on salary and gender estimating who will purchase the product

In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [64]:
data = pd.read_csv('ads.csv')

In [65]:
data.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [66]:
x = data.iloc[:,2:3].values
y = data.iloc[:,4].values

In [67]:
print("First five elements of x:", x[0 :5])
print("First five elements of y:", y[0 :5])

First five elements of x: [[19]
 [35]
 [26]
 [27]
 [19]]
First five elements of y: [0 0 0 0 0]


Splitting into training and tests sets

In [68]:
from sklearn.cross_validation import train_test_split
X_train , X_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [69]:
print("First five elements of X_train:", x[0 :5])
print("First five elements of X_test:", y[0 :5])
print("First five elements of y_train:", x[0 :5])
print("First five elements of y_test:", y[0 :5])

First five elements of X_train: [[19]
 [35]
 [26]
 [27]
 [19]]
First five elements of X_test: [0 0 0 0 0]
First five elements of y_train: [[19]
 [35]
 [26]
 [27]
 [19]]
First five elements of y_test: [0 0 0 0 0]


Scaling

In [70]:
from sklearn.preprocessing import StandardScaler
x1 = StandardScaler()
X_train = x1.fit_transform(X_train)
X_test = x1.transform(X_test)

C:\Users\Hope\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


Fitting Logistic REgression Model

In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
logreg = LogisticRegression(random_state=0)
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

Prediction

In [73]:
pred = logreg.predict(X_test)

In [74]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

Confusion Matrix

In [75]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)

In [76]:
cm

array([[66,  2],
       [ 8, 24]], dtype=int64)

In [77]:
66+24

90

Correct predictions and 10 wrong predictions

# K-Nearest Neighbor 

In [81]:
from sklearn.neighbors import KNeighborsClassifier

In [82]:
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [83]:
ypred = knn.predict(X_test)

In [84]:
from sklearn.metrics import confusion_matrix
con  = confusion_matrix(y_test,ypred)

In [85]:
con

array([[62,  6],
       [ 7, 25]], dtype=int64)

In [86]:
62+25

87

87 correct predictions and 13 wrong

# Support Vector Machine (SVM)

In [87]:
from sklearn.svm import SVC

In [88]:
svc = SVC(kernel='linear',random_state=0)
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [89]:
svc_pred = svc.predict(X_test)

In [90]:
from sklearn.metrics import confusion_matrix
conf  = confusion_matrix(y_test,svc_pred)

In [91]:
conf

array([[66,  2],
       [ 8, 24]], dtype=int64)

In [92]:
66+24

90

90 correct predictions and 10 wrong

# kernal SVM

In [93]:
svc = SVC(kernel='rbf',random_state=0)
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [94]:
kernal_pred = svc.predict(X_test)

In [95]:
from sklearn.metrics import confusion_matrix
conff  = confusion_matrix(y_test,kernal_pred)

In [96]:
conff

array([[66,  2],
       [ 9, 23]], dtype=int64)

In [97]:
66+23


89

89 correct predictions

#  Naive Bayes 

In [99]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB(priors=None)

In [100]:
gnb_pred = gnb.predict(X_test)

In [101]:
from sklearn.metrics import confusion_matrix
confusion  = confusion_matrix(y_test,gnb_pred)

In [102]:
confusion


array([[66,  2],
       [ 8, 24]], dtype=int64)

In [103]:
66+24

90

90 correct predictions

# Decision Tree Classification 

In [104]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy' , random_state=0)
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [105]:
dtc_pred = dtc.predict(X_test)

In [106]:
dtc_pred


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [107]:
from sklearn.metrics import confusion_matrix
confus  = confusion_matrix(y_test,dtc_pred)

In [108]:
confus

array([[63,  5],
       [ 8, 24]], dtype=int64)

In [109]:
63+24

87

87 correct predictions

# Random Forest Classification 

In [114]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10 , criterion = 'entropy' , random_state=0)
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [115]:
rfc_pred = rfc.predict(X_test)

In [116]:
from sklearn.metrics import confusion_matrix
confuss  = confusion_matrix(y_test,rfc_pred)

In [117]:
confuss

array([[63,  5],
       [ 8, 24]], dtype=int64)

In [118]:
63+24

87

87 correct predictions