# Simple Linear Regression

Import the libs


In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importing the data

In [5]:
data = pd.read_csv("salary.csv")

In [7]:
data.head(10)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0

Seggrigating Dependent and independent variables

In [11]:
x = data.iloc[:,:-1].values
y = data.iloc[:,1].values

In [22]:
print("First five elements:", x[0 :5])


First five elements: [[1.1]
 [1.3]
 [1.5]
 [2. ]
 [2.2]]


In [18]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

Splitting into train test

In [23]:
from sklearn.cross_validation import train_test_split

In [24]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.30 ,random_state = 0)

Fitting Simple linear Regression

In [25]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

Predicting the test Cases

In [36]:
pred = reg.predict(x_test)

In [37]:
pred

array([ 40817.78327049, 123188.08258899,  65154.46261459,  63282.41035735,
       115699.87356004, 108211.66453108, 116635.89968866,  64218.43648597,
        76386.77615802])

Visualizing the test results


In [44]:
plt.scatter(x_test,y_test,color = "orange")
plt.plot(x_train,reg.predict(x_train),color = "blue")
plt.title("salary predictions")
plt.xlabel('exp in years')
plt.ylabel("salaries")


Text(0,0.5,'salaries')

Predictions if exp is 0.5 salary?


In [46]:
pred = reg.predict(0.5)
pred

array([31457.52198429])